import { useEffect, useRef, useState } from 'react'
import { AlertCircle, Check, ChevronDown, ChevronUp, Download, History, LoaderCircle, Maximize2, Minimize2, Plus, Save, Send, Trash2 } from 'lucide-react'
import { createEditorDraft, editorDownloadUrl, getEditorDraft, getEditorExternalChange, getEditorVersions, previewUrl, publishEditorDraft, resolveEditorExternalChange, rollbackEditorVersion, updateEditorDraft, type EditorVersion } from '../api/client'

type Lang = 'zh' | 'en'; type Bi = { zh: string; en: string }
type Entry = Record<string, unknown> & { title?: Bi; org?: Bi; location?: Bi; date?: Bi; summary?: Bi; items?: Bi[]; responsibilities?: Bi[] }
type Section = Record<string, unknown> & { type: string; title: Bi; body?: Bi; rows?: Array<{ label: Bi; items: Bi }>; entries?: Entry[] }
type Resume = { meta: Record<string, unknown> & { name: Bi; position: Bi; contacts?: Record<string, string> }; sections: Section[] }
const bi = (): Bi => ({ zh: '', en: '' }); const copy = <T,>(x: T) => JSON.parse(JSON.stringify(x)) as T
const newEntry = (): Entry => ({ title: bi(), org: bi(), location: bi(), date: bi(), items: [] })
const newSection = (type = 'entries'): Section => type === 'paragraph' ? { type, title: bi(), body: bi() } : type === 'skills' ? { type, title: bi(), rows: [] } : { type, title: bi(), entries: [] }
function move<T>(items: T[], i: number, by: number) { const j = i + by; if (j >= 0 && j < items.length) [items[i], items[j]] = [items[j], items[i]] }

function BiInput({ label, value, onChange, multi = false }: { label: string; value: Bi; onChange: (x: Bi) => void; multi?: boolean }) { const Tag = multi ? 'textarea' : 'input'; return <label className="bi-field"><span>{label}</span><Tag value={value?.zh ?? ''} placeholder="中文" onChange={(e) => onChange({ ...value, zh: e.target.value })}/><Tag value={value?.en ?? ''} placeholder="English" onChange={(e) => onChange({ ...value, en: e.target.value })}/></label> }
function IconActions({ up, down, del }: { up: () => void; down: () => void; del: () => void }) { return <div className="row-actions"><button onClick={up}><ChevronUp size={15}/></button><button onClick={down}><ChevronDown size={15}/></button><button className="danger" onClick={del}><Trash2 size={15}/></button></div> }

function Bullets({ values, update }: { values: Bi[]; update: (x: Bi[]) => void }) { return <div className="bullets"><strong>描述</strong>{values.map((value, i) => <div key={i}><BiInput label={`第 ${i + 1} 条`} value={value} multi onChange={(v) => { const n = [...values]; n[i] = v; update(n) }}/><button className="danger" onClick={() => update(values.filter((_, x) => x !== i))}><Trash2 size={15}/></button></div>)}<button onClick={() => update([...values, bi()])}><Plus size={15}/>新增描述</button></div> }
function Entries({ section, update }: { section: Section; update: (fn: (s: Section) => void) => void }) { const entries = section.entries ?? []; return <>{entries.map((entry, i) => <div className="nested-card" key={i}><IconActions up={() => update((s) => move(s.entries!, i, -1))} down={() => update((s) => move(s.entries!, i, 1))} del={() => update((s) => s.entries!.splice(i, 1))}/>{(['title', 'org', 'location', 'date'] as const).map((field) => <BiInput key={field} label={field} value={entry[field] ?? bi()} onChange={(v) => update((s) => { s.entries![i][field] = v })}/>)}{('summary' in entry || section.type === 'entries') && <BiInput label="项目简介" value={entry.summary ?? bi()} multi onChange={(v) => update((s) => { s.entries![i].summary = v })}/>}<Bullets values={entry.responsibilities ?? entry.items ?? []} update={(v) => update((s) => { if ('responsibilities' in entry || section.type === 'entries') s.entries![i].responsibilities = v; else s.entries![i].items = v })}/></div>)}<button onClick={() => update((s) => s.entries!.push(newEntry()))}><Plus size={16}/>新增条目</button></> }
function Skills({ section, update }: { section: Section; update: (fn: (s: Section) => void) => void }) { const rows = section.rows ?? []; return <>{rows.map((row, i) => <div className="nested-card" key={i}><IconActions up={() => update((s) => move(s.rows!, i, -1))} down={() => update((s) => move(s.rows!, i, 1))} del={() => update((s) => s.rows!.splice(i, 1))}/><BiInput label="技能分类" value={row.label} onChange={(v) => update((s) => { s.rows![i].label = v })}/><BiInput label="技能内容" value={row.items} onChange={(v) => update((s) => { s.rows![i].items = v })}/></div>)}<button onClick={() => update((s) => s.rows!.push({ label: bi(), items: bi() }))}><Plus size={16}/>新增技能分类</button></> }

export default function ResumeEditorPage() {
  const [id, setId] = useState<string>(), [resume, setResume] = useState<Resume>(), [state, setState] = useState('loading'), [error, setError] = useState(''), [lang, setLang] = useState<Lang>('zh'), [rev, setRev] = useState(0), [conflict, setConflict] = useState(false), [history, setHistory] = useState<EditorVersion[]>([]), [versions, setVersions] = useState(false), [publish, setPublish] = useState(false), [fullscreen, setFullscreen] = useState(false), [message, setMessage] = useState('发布版本')
  const timer = useRef<number | undefined>(undefined), latest = useRef<Resume | undefined>(undefined)
  const load = async (runId: string) => { const [draft, list] = await Promise.all([getEditorDraft(runId), getEditorVersions(runId)]); latest.current = draft as Resume; setResume(latest.current); setHistory(list); setState('saved') }
  useEffect(() => { createEditorDraft().then((draft) => { setId(draft.run_id); return load(draft.run_id) }).catch((e) => { setError(e.message); setState('error') }); return () => window.clearTimeout(timer.current) }, [])
  useEffect(() => { if (!id) return; const interval = window.setInterval(() => getEditorExternalChange(id).then((x) => setConflict(x.changed)).catch(() => undefined), 2000); return () => window.clearInterval(interval) }, [id])
  const persist = async (next: Resume) => { if (!id) return; try { await updateEditorDraft(id, next as unknown as Record<string, unknown>); setState('saved'); setError(''); setRev((n) => n + 1) } catch (e) { setState('error'); setError(e instanceof Error ? e.message : '保存失败') } }
  const change = (fn: (d: Resume) => void) => { if (!resume) return; const next = copy(resume); fn(next); latest.current = next; setResume(next); setState('saving'); window.clearTimeout(timer.current); timer.current = window.setTimeout(() => persist(next), 650) }
  const resolve = async (action: 'reload' | 'keep') => { if (!id) return; await resolveEditorExternalChange(id, action); if (action === 'reload') await load(id); setConflict(false) }
  const doPublish = async () => { if (!id || !latest.current) return; await persist(latest.current); await publishEditorDraft(id, message); setHistory(await getEditorVersions(id)); setPublish(false) }
  if (!resume || !id) return <div className="card">正在准备唯一编辑草稿…</div>
  return <div><div className="page-header"><div><h1>修改基线版本</h1><p>唯一草稿自动保存；确认发布后才更新 Master Resume 基线。</p></div><div className={`editor-save-state ${state}`}>{state === 'saving' || state === 'loading' ? <LoaderCircle size={16} className="spin"/> : state === 'error' ? <AlertCircle size={16}/> : <Check size={16}/>}{state === 'saving' ? '正在保存' : state === 'error' ? '保存失败' : '已保存'}</div></div>
    {conflict && <div className="card callout conflict"><AlertCircle size={18}/><span>本地 resume.yaml 已被修改。</span><button className="secondary" onClick={() => void resolve('reload')}>重新载入本地版本</button><button onClick={() => void resolve('keep')}>保留网页草稿</button></div>}{error && <div className="card callout-danger">{error}</div>}
    <div className="editor-toolbar card"><div><button className="secondary" onClick={() => { if (latest.current) void persist(latest.current) }}><Save size={16}/>立即保存</button><button className="secondary" onClick={() => setVersions(!versions)}><History size={16}/>版本历史</button></div><div><a className="button secondary" href={editorDownloadUrl(id, 'html', lang)}><Download size={16}/>HTML</a><a className="button secondary" href={editorDownloadUrl(id, 'pdf', lang)}><Download size={16}/>PDF</a><button className="publish-button" onClick={() => setPublish(true)}><Send size={16}/>发布到 Master</button></div></div>
    {versions && <div className="card version-list"><h2>发布历史</h2>{history.slice().reverse().map((v) => <div key={v.id}><span>{v.message}</span><small>{new Date(v.created_at).toLocaleString()}</small><button className="secondary" onClick={() => { if (window.confirm(`回退至 ${v.id} 并发布到 Master？`)) rollbackEditorVersion(id, v.id).then(() => load(id)) }}>回退</button></div>)}</div>}
    {publish && <div className="modal-backdrop"><div className="modal card"><h2>发布到 Master Resume</h2><p>将覆盖唯一的 <code>web/data/resume.yaml</code>，并自动创建可回退版本。</p><input value={message} onChange={(e) => setMessage(e.target.value)}/><div><button onClick={() => setPublish(false)}>取消</button><button className="publish-button" onClick={() => void doPublish()}>确认发布</button></div></div></div>}
    <div className="editor-layout"><section className="card structured-editor"><h2>基本信息</h2><BiInput label="姓名" value={resume.meta.name} onChange={(v) => change((d) => { d.meta.name = v })}/><BiInput label="职位" value={resume.meta.position} onChange={(v) => change((d) => { d.meta.position = v })}/><div className="contact-grid">{Object.entries(resume.meta.contacts ?? {}).map(([key, value]) => <label key={key}>{key}<input value={value} onChange={(e) => change((d) => { (d.meta.contacts ??= {})[key] = e.target.value })}/></label>)}</div><div className="section-heading"><h2>简历模块</h2><button className="secondary" onClick={() => change((d) => d.sections.push(newSection()))}><Plus size={16}/>新增模块</button></div>{resume.sections.map((section, i) => <article className="edit-section" key={i}><div className="row-actions"><select value={section.type} onChange={(e) => change((d) => { d.sections[i] = { ...newSection(e.target.value), title: d.sections[i].title } })}><option value="entries">经历 / 项目</option><option value="education">教育经历</option><option value="skills">技能</option><option value="paragraph">段落</option></select><IconActions up={() => change((d) => move(d.sections, i, -1))} down={() => change((d) => move(d.sections, i, 1))} del={() => change((d) => d.sections.splice(i, 1))}/></div><BiInput label="模块标题" value={section.title} onChange={(v) => change((d) => { d.sections[i].title = v })}/>{section.type === 'paragraph' && <BiInput label="内容" value={section.body ?? bi()} multi onChange={(v) => change((d) => { d.sections[i].body = v })}/>} {section.type === 'skills' ? <Skills section={section} update={(fn) => change((d) => fn(d.sections[i]))}/> : section.type !== 'paragraph' && <Entries section={section} update={(fn) => change((d) => fn(d.sections[i]))}/>}</article>)}</section><section className={`card preview-pane ${fullscreen ? 'preview-fullscreen' : ''}`}><div className="preview-toolbar"><div><h2>实时预览</h2><p className="muted">保存成功后自动更新。</p></div><div className="preview-actions"><div className="lang-toggle"><button className={lang === 'zh' ? 'active' : ''} onClick={() => setLang('zh')}>中文</button><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>English</button></div><button className="secondary" onClick={() => setFullscreen(!fullscreen)}>{fullscreen ? <Minimize2 size={16}/> : <Maximize2 size={16}/>}{fullscreen ? '退出全屏' : '全屏预览'}</button></div></div><iframe key={`${lang}-${rev}`} className="preview-frame" title="实时简历预览" src={previewUrl(id, lang)}/></section></div></div>
}
