import { useRef } from 'react'
import { Check, Copy, Download, FilePenLine, FileUp, Trash2 } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { copyTemplate, deleteTemplate, importTemplate, listTemplates, renameTemplate, setActiveTemplate } from '../api/client'

export default function TemplatesPage() {
  const input = useRef<HTMLInputElement>(null), queryClient = useQueryClient()
  const templates = useQuery({ queryKey: ['templates'], queryFn: listTemplates })
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['templates'] })
  const activate = useMutation({ mutationFn: setActiveTemplate, onSuccess: refresh })
  const remove = useMutation({ mutationFn: deleteTemplate, onSuccess: refresh })
  const rename = useMutation({ mutationFn: ({ id, name }: { id: string; name: string }) => renameTemplate(id, name), onSuccess: refresh })
  const duplicate = useMutation({ mutationFn: ({ source, id, name }: { source: string; id: string; name: string }) => copyTemplate(source, id, name), onSuccess: refresh })
  const upload = async (file?: File) => { if (!file) return; await importTemplate(file); await refresh() }
  const copy = (template: { id: string; name: string }) => { const id = window.prompt('新模板 ID（小写字母、数字、- 或 _）'); const name = window.prompt('新模板名称', `${template.name} 副本`); if (id && name) duplicate.mutate({ source: template.id, id, name }) }
  const editName = (template: { id: string; name: string }) => { const name = window.prompt('模板名称', template.name); if (name) rename.mutate({ id: template.id, name }) }
  return <div><div className="page-header"><div><h1>模板管理</h1><p>切换后会统一应用到基线、所有版本预览和 HTML/PDF 下载。</p></div><button onClick={() => input.current?.click()}><FileUp size={16}/>导入模板包</button><input className="template-file-input" ref={input} type="file" accept=".zip" onChange={(e) => void upload(e.target.files?.[0])}/></div><div className="template-grid">{(templates.data ?? []).map((template) => <article className={`card template-card template-${template.id} ${template.active ? 'active' : ''}`} key={template.id}><div className="template-preview"><div className="sample-name">YOUR NAME</div><div className="sample-role">SOFTWARE ENGINEER</div><div className="sample-rule"/><div className="sample-heading">EXPERIENCE</div><div className="sample-line wide"/><div className="sample-line"/><div className="sample-line short"/><div className="sample-heading">PROJECTS</div><div className="sample-line wide"/><div className="sample-line"/></div><div className="template-title"><div><h2>{template.name}</h2><p>{template.description}</p></div>{template.active && <span className="template-active"><Check size={14}/>当前使用</span>}</div>{template.unsupported.length > 0 && <p className="muted">将隐藏：{template.unsupported.join('、')}</p>}<div className="template-actions"><button className="secondary" disabled={template.active || activate.isPending} onClick={() => activate.mutate(template.id)}>应用模板</button><button className="secondary" onClick={() => copy(template)}><Copy size={15}/>复制</button>{!template.builtin && <><button className="secondary" onClick={() => editName(template)}><FilePenLine size={15}/>重命名</button><a className="button secondary" href={`/api/v1/resume/templates/${template.id}/export`}><Download size={15}/>导出</a><button className="secondary danger" disabled={template.active || remove.isPending} onClick={() => { if (window.confirm(`删除模板“${template.name}”？`)) remove.mutate(template.id) }}><Trash2 size={15}/>删除</button></>}</div></article>)}</div>{templates.error && <p className="error-text">{(templates.error as Error).message}</p>}<div className="card template-help"><h2>自定义模板包规范</h2><code>manifest.json + theme.css + assets/</code><p>模板只能覆盖固定简历结构的样式；不允许脚本、远程资源或 @import。可包含本地图片与字体。</p><a className="button secondary" href="/api/v1/resume/templates/specification"><Download size={15}/>下载模板包规范</a></div></div>
}
